# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/poe-build-embedder',
                'doc_host': 'https://DataAndDeadlifts.github.io',
                'git_url': 'https://github.com/DataAndDeadlifts/poe-build-embedder',
                'lib_path': 'poe_build_embedder'},
  'syms': { 'poe_build_embedder.core': {'poe_build_embedder.core.foo': ('core.html#foo', 'poe_build_embedder/core.py')},
            'poe_build_embedder.get.characters': { 'poe_build_embedder.get.characters.Requester': ( 'get.characters.html#requester',
                                                                                                    'poe_build_embedder/get/characters.py'),
                                                   'poe_build_embedder.get.characters.Requester.__init__': ( 'get.characters.html#requester.__init__',
                                                                                                             'poe_build_embedder/get/characters.py'),
                                                   'poe_build_embedder.get.characters.Requester.get': ( 'get.characters.html#requester.get',
                                                                                                        'poe_build_embedder/get/characters.py'),
                                                   'poe_build_embedder.get.characters.Requester.get_character_items': ( 'get.characters.html#requester.get_character_items',
                                                                                                                        'poe_build_embedder/get/characters.py'),
                                                   'poe_build_embedder.get.characters.Requester.get_character_tree': ( 'get.characters.html#requester.get_character_tree',
                                                                                                                       'poe_build_embedder/get/characters.py')}}}
